##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.18.0-B7] date: [Thu Apr 13 18:20:17 CST 2023] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------


######################################
# target
######################################
TARGET = basic_framework


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og
ROBOT_TYPE ?= infantry
ifeq ($(strip $(ROBOT_TYPE)),)
override ROBOT_TYPE := infantry
endif


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################

PROJ_DIR = Src \
Inc \
application \
modules \
bsp \
Drivers \
Middlewares

# 快速递归搜索当前目录下的.c文件,需在msys2/MinGW环境使用(Windows下),linux/macOS则可以直接使用
# windows下使用命令行(cmd)或powershell时,替换注释的内容.

# for unix/linux/macOS or Msys2/MinGW bash:
ALL_DIRS := $(foreach dire, $(PROJ_DIR), $(shell find $(dire) -maxdepth 10 -type d))
# for windows cmd/pwsh:
# SHELL = cmd
# ALL_DIRS := $(foreach dire, $(PROJ_DIR), $(shell dir $(dire) /s /b /a:d))
# ALL_DIRS += $(PROJ_DIR)


C_SOURCES := $(foreach dire, $(ALL_DIRS), $(wildcard $(dire)/*.c))

# ASM sources
ASM_SOURCES =  \
startup_stm32f407xx.s \
Middlewares/Third_Party/SEGGER/RTT/SEGGER_RTT_ASM_ARMv7M.s 


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb -mthumb-interwork $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F407xx \
-DARM_MATH_CM4 \
-DROBOT_TYPE_$(ROBOT_TYPE) \
-DDISABLE_LOG_SYSTEM # 关闭日志系统

# AS includes
AS_INCLUDES =  \
-IInc

# C includes
# 快速递归添加包含目录
C_INCLUDES := $(addprefix -I,$(ALL_DIRS))


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -fdata-sections -ffunction-sections -fmessage-length=0

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F407IGHx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys  \
-l:libCMSISDSP.a  # 若想要自行编译CMSIS-DSP库,请参考https://github.com/ARM-software/CMSIS-DSP
LIBDIR =  \
-LMiddlewares/ST/ARM/DSP/Lib
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections -flto

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin

# 帮助信息
help:
	@echo "=========================================="
	@echo "  Basic Framework - 跨平台Makefile帮助"
	@echo "=========================================="
	@echo ""
	@echo "编译目标:"
	@echo "  make / make all    - 编译项目（生成.elf, .hex, .bin）"
	@echo "  make clean         - 清理编译文件"
	@echo "  make rebuild       - 重新编译（clean + build）"
	@echo ""
	@echo "烧录目标 (会自动先编译):"
	@echo "  make flash         - 默认烧录方式（DFU-Util，推荐）"
	@echo "  make flash_dfu     - 使用DFU-Util烧录（USB，跨平台）"
	@echo "  make flash_dap     - 使用OpenOCD + DAP-Link烧录"
	@echo "  make flash_stlink  - 使用OpenOCD + ST-Link烧录"
	@echo "  make flash_jlink   - 使用JFlash烧录（需JFlash）"
	@echo ""
	@echo "传统兼容命名:"
	@echo "  make download_dap  - 同 flash_dap"
	@echo "  make download_jlink- 同 flash_jlink"
	@echo ""
	@echo "使用示例:"
	@echo "  make -j12          - 12线程并行编译"
	@echo "  make ROBOT_TYPE=infantry - 指定机器人配置"
	@echo "  make clean flash   - 清理后重新编译并烧录"
	@echo ""
	@echo "平台说明:"
	@echo "  Mac/Linux: 直接使用 'make'"
	@echo "  Windows:   使用 'mingw32-make'"
	@echo ""
	@echo "更多信息请查看: 跨平台配置指南.md"
	@echo "=========================================="


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	@$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	@$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	@$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	@mkdir $@		


#######################################
# clean up
#######################################
clean:
	rm -rf $(BUILD_DIR)


#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)


#######################################
# download/flash targets
#######################################
FLASH_START = 0x08000000

# DFU烧录 (通过USB DFU模式，跨平台)
flash_dfu: $(BUILD_DIR)/$(TARGET).bin
	dfu-util -a 0 -s $(FLASH_START):leave -D $(BUILD_DIR)/$(TARGET).bin

# OpenOCD + DAP-Link烧录 (Mac/Linux/Windows with MSYS2)
flash_dap: $(BUILD_DIR)/$(TARGET).bin
	openocd -f openocd_dap.cfg -c init -c halt -c "flash write_image erase $(BUILD_DIR)/$(TARGET).bin $(FLASH_START)" -c reset -c shutdown

# OpenOCD + ST-Link烧录 (跨平台)
flash_stlink: $(BUILD_DIR)/$(TARGET).elf
	openocd -d1 -f interface/stlink.cfg -f target/stm32f4x.cfg -c "init; reset init; program $(BUILD_DIR)/$(TARGET).elf verify reset exit"

# JLink烧录 (需要JFlash，主要Windows)
flash_jlink: $(BUILD_DIR)/$(TARGET).hex
	JFlash -openprj'stm32.jflash' -open'$(BUILD_DIR)/$(TARGET).hex',$(FLASH_START) -auto -startapp -exit

# 传统命名兼容 (保留向后兼容性)
download_dap: flash_dap
download_jlink: flash_jlink

# 默认烧录方式 (推荐使用dfu-util，跨平台且无需额外硬件)
flash: flash_dfu

# 重新编译（先清理再编译）
rebuild: clean all

.PHONY: all clean rebuild flash flash_dfu flash_dap flash_stlink flash_jlink download_dap download_jlink help

# *** EOF ***
